################################################################################
# Main configs
################################################################################
timestep: &timestep 0.002
scale: 3.0
duration: 10 #[s]


################################################################################
# robot configs
################################################################################
sim_robot_variables:
  xml_filename: "/models/b2z1/b2z1_copy.xml"
  urdf_filename: "/models/b2z1_copy.urdf"

  use_fixed_base: False

  base_name: "base_link"
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
  ]  # pinocchio order
  limb_names: ["FL", "FR", "RL", "RR"]
  limb_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]

  base_init_pos: [0., 0., 0.50, 0., 0., 0., 1.] # pose
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5,
                   ]
  joint_init_vel: [0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   ]


################################################################################
# control configs
################################################################################
controller_variables:
  xml_filename: "/models/b2z1/b2z1_copy.xml"
  urdf_filename: "/models/b2z1_copy.urdf"

  base_name: "base_link"
  leg_names: ["FL", "FR", "RL", "RR"]
  arm_names: []
  limb_names: ["FL", "FR", "RL", "RR"]
  leg_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]
  arm_endeff_names: []
  limb_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
    ]  # pinocchio order
  torque_limits: [200, 200, 320, 
                  200, 200, 320, 
                  200, 200, 320, 
                  200, 200, 320,
                  ]
  torque_factor: 0.5
  fric_coef: 0.5
  timestep: 0.002
  joint_kp: [0, 0, 0, 
             0, 0, 0, 
             0, 0, 0, 
             0, 0, 0,
             ]
  joint_kd: [0, 0, 0, 
             0, 0, 0, 
             0, 0, 0, 
             0, 0, 0,
             ]

  # task-space / joint-space gains
  kp_com_pos: [95., 95., 100.]
  kd_com_pos: [20, 20, 20.]
  kp_base_pos: [95., 95., 100.]
  kd_base_pos: [20., 20., 20.]
  kp_base_orn: [200., 200., 50.]
  kd_base_orn: [20., 20., 20.]
  kp_nom_pos: [
    1., 1., 1.,  
    1., 1., 1.,  
    1., 1., 1.,  
    1., 1., 1.,
    
  ]
  kd_nom_pos: [
    0.01, 0.01, 0.01,  
    0.01, 0.01, 0.01,  
    0.01, 0.01, 0.01,  
    0.01, 0.01, 0.01, 
  ]
  kp_leg_endeff_pos: [250., 250., 300.]
  kd_leg_endeff_pos: [60., 60., 70.]
  kp_leg_endeff_orn: [100., 100., 100.]
  kd_leg_endeff_orn: [10., 10., 10.]
  kp_arm_endeff_pos: [300., 300., 300.]
  kd_arm_endeff_pos: [30., 30., 30.]
  kp_arm_endeff_orn: [100., 100., 100.]
  kd_arm_endeff_orn: [10., 10., 10.]

  joint_init_pos: [0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5,
                   ]
  joint_init_vel: [0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0.,
                   ]


################################################################################
# planning configs
################################################################################
planner_variables:
  task_hierarchy: {
    "dynamic_consistency_task": {"priority": 0, "weight": 1},
    "contact_motion_task": {"priority": 1, "weight": 1}, 
    "base_position_task": {"priority": 2, "weight": 1}, 
    "base_orientation_task": {"priority": 2, "weight": 1},
    "swing_leg_endeff_position_task": {"priority": 2, "weight": 0.5}, 
    # "swing_arm_endeff_position_task": {"priority": 3, "weight": 0.5},
    # "swing_arm_endeff_orientation_task": {"priority": 3, "weight": 0.5},
    # "minimum_motion_task": {"priority": 3, "weight": 1.0}
  }

  base_name: "base_link"
  leg_names: ["FL", "FR", "RL", "RR"]
  arm_names: []
  leg_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]
  arm_endeff_names: []

  base_des_pos: [0., 0., 0.5, 0., 0., 0., 1.] # pose
  base_des_vel: [0., 0., 0., 0., 0., 0.]
  joint_des_pos: [0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5,
                  ]
  joint_des_vel: [0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0.,
                  ]
  arm_des_pos: [0.6, 0., 0.845942, 0., 0., 0., -1.]
  arm_des_vel: [0., 0., 0., 0., 0., 0.]